package com.chinasofti.model;

import org.springframework.stereotype.Component;

@Component
public class Company_user {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column company_user.cuser_id
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 企业用户ID
	 */
	private Integer cuserId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column company_user.cname
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 企业用户帐号
	 */
	private String cname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column company_user.cpwd
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 企业用户密码
	 */
	private String cpwd;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column company_info.com_name
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 公司名称
	 */
	private String comName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column company_info.com_field
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 公司领域
	 */
	private String comField;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column company_info.com_num
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 公司人数
	 */
	private Integer comNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column company_info.com_add
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 公司地址
	 */
	private String comAdd;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column company_info.com_info
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 公司信息
	 */
	private String comInfo;

	public Integer getCuserId() {
		return cuserId;
	}

	public void setCuserId(Integer cuserId) {
		this.cuserId = cuserId;
	}

	public String getCname() {
		return cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public String getCpwd() {
		return cpwd;
	}

	public void setCpwd(String cpwd) {
		this.cpwd = cpwd;
	}

	public String getComName() {
		return comName;
	}

	public void setComName(String comName) {
		this.comName = comName;
	}

	public String getComField() {
		return comField;
	}

	public void setComField(String comField) {
		this.comField = comField;
	}

	public Integer getComNum() {
		return comNum;
	}

	public void setComNum(Integer comNum) {
		this.comNum = comNum;
	}

	public String getComAdd() {
		return comAdd;
	}

	public void setComAdd(String comAdd) {
		this.comAdd = comAdd;
	}

	public String getComInfo() {
		return comInfo;
	}

	public void setComInfo(String comInfo) {
		this.comInfo = comInfo;
	}

	@Override
	public String toString() {
		return "Company_user [cuserId=" + cuserId + ", cname=" + cname + ", cpwd=" + cpwd + ", comName=" + comName
				+ ", comField=" + comField + ", comNum=" + comNum + ", comAdd=" + comAdd + ", comInfo=" + comInfo + "]";
	}

	public Company_user(Integer cuserId, String cname, String cpwd, String comName, String comField, Integer comNum,
			String comAdd, String comInfo) {
		super();
		this.cuserId = cuserId;
		this.cname = cname;
		this.cpwd = cpwd;
		this.comName = comName;
		this.comField = comField;
		this.comNum = comNum;
		this.comAdd = comAdd;
		this.comInfo = comInfo;
	}

	public Company_user(String comName, String comField, Integer comNum, String comAdd, String comInfo) {
		super();
		this.comName = comName;
		this.comField = comField;
		this.comNum = comNum;
		this.comAdd = comAdd;
		this.comInfo = comInfo;
	}

	public Company_user(Integer cuserId, String cname, String cpwd) {
		super();
		this.cuserId = cuserId;
		this.cname = cname;
		this.cpwd = cpwd;
	}

	public Company_user(String cname, String cpwd) {
		super();
		this.cname = cname;
		this.cpwd = cpwd;
	}

	public Company_user() {
		super();
		// TODO Auto-generated constructor stub
	}

}