package com.chinasofti.model;

import org.springframework.stereotype.Component;

@Component
public class Company_user {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column company_user.cuser_id
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 企业用户ID
	 */
	private Integer cuserId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column company_user.cname
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 企业用户帐号
	 */
	private String cname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column company_user.cpwd
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 企业用户密码
	 */
	private String cpwd;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column company_user.com_id
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 s所属公司ID
	 */
	private Integer comId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column company_user.cuser_id
	 *
	 * @return the value of company_user.cuser_id
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017
	 */
	public Integer getCuserId() {
		return cuserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column company_user.cuser_id
	 *
	 * @param cuserId
	 *            the value for company_user.cuser_id
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017
	 */
	public void setCuserId(Integer cuserId) {
		this.cuserId = cuserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column company_user.cname
	 *
	 * @return the value of company_user.cname
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017
	 */
	public String getCname() {
		return cname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column company_user.cname
	 *
	 * @param cname
	 *            the value for company_user.cname
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017
	 */
	public void setCname(String cname) {
		this.cname = cname == null ? null : cname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column company_user.cpwd
	 *
	 * @return the value of company_user.cpwd
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017
	 */
	public String getCpwd() {
		return cpwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column company_user.cpwd
	 *
	 * @param cpwd
	 *            the value for company_user.cpwd
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017
	 */
	public void setCpwd(String cpwd) {
		this.cpwd = cpwd == null ? null : cpwd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column company_user.com_id
	 *
	 * @return the value of company_user.com_id
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017
	 */
	public Integer getComId() {
		return comId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column company_user.com_id
	 *
	 * @param comId
	 *            the value for company_user.com_id
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017
	 */
	public void setComId(Integer comId) {
		this.comId = comId;
	}

	public Company_user(Integer cuserId, String cname, String cpwd, Integer comId) {
		super();
		this.cuserId = cuserId;
		this.cname = cname;
		this.cpwd = cpwd;
		this.comId = comId;
	}

	public Company_user(String cname, String cpwd) {
		super();
		this.cname = cname;
		this.cpwd = cpwd;
	}

	public Company_user() {
		super();
		// TODO Auto-generated constructor stub
	}

	@Override
	public String toString() {
		return "Company_user [cuserId=" + cuserId + ", cname=" + cname + ", cpwd=" + cpwd + ", comId=" + comId + "]";
	}
}