package com.chinasofti.model;

import org.springframework.stereotype.Component;

@Component
public class Company_info {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column company_info.com_id
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 公司ID
	 */
	private Integer comId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column company_info.com_name
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 公司名称
	 */
	private String comName;

	@Override
	public String toString() {
		return "Company_info [comId=" + comId + ", comName=" + comName + ", comField=" + comField + ", comNum=" + comNum
				+ ", comAdd=" + comAdd + ", comInfo=" + comInfo + "]";
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column company_info.com_field
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 公司领域
	 */
	private String comField;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column company_info.com_num
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 公司人数
	 */
	private Integer comNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column company_info.com_add
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 公司地址
	 */
	private String comAdd;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column company_info.com_info
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 公司信息
	 */
	private String comInfo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column company_info.com_id
	 *
	 * @return the value of company_info.com_id
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017
	 */
	public Integer getComId() {
		return comId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column company_info.com_id
	 *
	 * @param comId
	 *            the value for company_info.com_id
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017
	 */
	public void setComId(Integer comId) {
		this.comId = comId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column company_info.com_name
	 *
	 * @return the value of company_info.com_name
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017
	 */
	public String getComName() {
		return comName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column company_info.com_name
	 *
	 * @param comName
	 *            the value for company_info.com_name
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017
	 */
	public void setComName(String comName) {
		this.comName = comName == null ? null : comName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column company_info.com_field
	 *
	 * @return the value of company_info.com_field
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017
	 */
	public String getComField() {
		return comField;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column company_info.com_field
	 *
	 * @param comField
	 *            the value for company_info.com_field
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017
	 */
	public void setComField(String comField) {
		this.comField = comField == null ? null : comField.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column company_info.com_num
	 *
	 * @return the value of company_info.com_num
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017
	 */
	public Integer getComNum() {
		return comNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column company_info.com_num
	 *
	 * @param comNum
	 *            the value for company_info.com_num
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017
	 */
	public void setComNum(Integer comNum) {
		this.comNum = comNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column company_info.com_add
	 *
	 * @return the value of company_info.com_add
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017
	 */
	public String getComAdd() {
		return comAdd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column company_info.com_add
	 *
	 * @param comAdd
	 *            the value for company_info.com_add
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017
	 */
	public void setComAdd(String comAdd) {
		this.comAdd = comAdd == null ? null : comAdd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column company_info.com_info
	 *
	 * @return the value of company_info.com_info
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017
	 */
	public String getComInfo() {
		return comInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column company_info.com_info
	 *
	 * @param comInfo
	 *            the value for company_info.com_info
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017
	 */
	public void setComInfo(String comInfo) {
		this.comInfo = comInfo == null ? null : comInfo.trim();
	}
}