package com.chinasofti.model;

import java.util.Date;

import org.springframework.stereotype.Component;
@Component
public class Edu_background {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_background.edu_id
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     * 教育背景ID
     */
    private Integer eduId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_background.sch_name
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     * 学校名称
     */
    private String schName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_background.maj_name
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     * 专业名称
     */
    private String majName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_background.edu
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     * 学历
     */
    private String edu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_background.edu_id
     *
     * @return the value of edu_background.edu_id
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public Integer getEduId() {
        return eduId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_background.edu_id
     *
     * @param eduId the value for edu_background.edu_id
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public void setEduId(Integer eduId) {
        this.eduId = eduId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_background.sch_name
     *
     * @return the value of edu_background.sch_name
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public String getSchName() {
        return schName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_background.sch_name
     *
     * @param schName the value for edu_background.sch_name
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public void setSchName(String schName) {
        this.schName = schName == null ? null : schName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_background.maj_name
     *
     * @return the value of edu_background.maj_name
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public String getMajName() {
        return majName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_background.maj_name
     *
     * @param majName the value for edu_background.maj_name
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public void setMajName(String majName) {
        this.majName = majName == null ? null : majName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_background.edu
     *
     * @return the value of edu_background.edu
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public String getEdu() {
        return edu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_background.edu
     *
     * @param edu the value for edu_background.edu
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public void setEdu(String edu) {
        this.edu = edu == null ? null : edu.trim();
    }
}