package com.chinasofti.model;

import java.util.Date;

public class job_info {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.job_id
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     * 工作ID
     */
    private Integer jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.job_name
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     * 工作名称
     */
    private String jobName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.job_sal
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     * 工作薪水
     */
    private Double jobSal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.job_year
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     * 工作要求年份
     */
    private String jobYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.job_edu
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     * 工作要求学历
     */
    private String jobEdu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.job_date
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     * 工作发布时间
     */
    private Date jobDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.job_welfare
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     * 职位福利
     */
    private String jobWelfare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.job_description
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     * 职位描述
     */
    private String jobDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.com_id
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     * 所属公司ID
     */
    private Integer comId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.job_id
     *
     * @return the value of job_info.job_id
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public Integer getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.job_id
     *
     * @param jobId the value for job_info.job_id
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.job_name
     *
     * @return the value of job_info.job_name
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.job_name
     *
     * @param jobName the value for job_info.job_name
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.job_sal
     *
     * @return the value of job_info.job_sal
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public Double getJobSal() {
        return jobSal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.job_sal
     *
     * @param jobSal the value for job_info.job_sal
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public void setJobSal(Double jobSal) {
        this.jobSal = jobSal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.job_year
     *
     * @return the value of job_info.job_year
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public String getJobYear() {
        return jobYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.job_year
     *
     * @param jobYear the value for job_info.job_year
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public void setJobYear(String jobYear) {
        this.jobYear = jobYear == null ? null : jobYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.job_edu
     *
     * @return the value of job_info.job_edu
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public String getJobEdu() {
        return jobEdu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.job_edu
     *
     * @param jobEdu the value for job_info.job_edu
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public void setJobEdu(String jobEdu) {
        this.jobEdu = jobEdu == null ? null : jobEdu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.job_date
     *
     * @return the value of job_info.job_date
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public Date getJobDate() {
        return jobDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.job_date
     *
     * @param jobDate the value for job_info.job_date
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public void setJobDate(Date jobDate) {
        this.jobDate = jobDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.job_welfare
     *
     * @return the value of job_info.job_welfare
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public String getJobWelfare() {
        return jobWelfare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.job_welfare
     *
     * @param jobWelfare the value for job_info.job_welfare
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public void setJobWelfare(String jobWelfare) {
        this.jobWelfare = jobWelfare == null ? null : jobWelfare.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.job_description
     *
     * @return the value of job_info.job_description
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public String getJobDescription() {
        return jobDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.job_description
     *
     * @param jobDescription the value for job_info.job_description
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public void setJobDescription(String jobDescription) {
        this.jobDescription = jobDescription == null ? null : jobDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.com_id
     *
     * @return the value of job_info.com_id
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.com_id
     *
     * @param comId the value for job_info.com_id
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }
}