package com.chinasofti.model;

import java.util.Date;

import org.springframework.stereotype.Component;

@Component
public class Personal_user {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column personal_user.pid
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 个人用户ID
	 */
	private Integer pid;

	public Personal_user(String pname, String ppwd) {
		super();
		this.pname = pname;
		this.ppwd = ppwd;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column personal_user.ppwd
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 个人用户密码
	 * 
	 */

	private String pname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column personal_user.sex
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 用户性别
	 */
	private String ppwd;

	private String puname;

	private String email;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column personal_user.pname
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 个人用户帐号
	 */

	private String sex;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column personal_user.birthday
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 用户出生日期
	 */
	private Integer age;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column edu_background.sch_name
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 学校名称
	 */
	private String schName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column edu_background.maj_name
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 专业名称
	 */
	private String majName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column edu_background.edu
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 学历
	 */
	private String edu;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column work_experience.com_name
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 公司名称
	 */
	private String workComName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column work_experience.job_name
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017
	 * 
	 *               职位名称
	 */
	private String workJobName;

	public Personal_user(String workComName, String workJobName, String workContent) {
		super();
		this.workComName = workComName;
		this.workJobName = workJobName;
		this.workContent = workContent;
	}


	public Personal_user(String puname, String email, String sex, Integer age) {
		super();
		this.puname = puname;
		this.email = email;
		this.sex = sex;
		this.age = age;
	}

	public Personal_user(Integer pid, String pname, String ppwd, String puname, String email, String sex, Integer age,
			String schName, String majName, String edu, String workComName, String workJobName, String workContent) {
		super();
		this.pid = pid;
		this.pname = pname;
		this.ppwd = ppwd;
		this.puname = puname;
		this.email = email;
		this.sex = sex;
		this.age = age;
		this.schName = schName;
		this.majName = majName;
		this.edu = edu;
		this.workComName = workComName;
		this.workJobName = workJobName;
		this.workContent = workContent;
	}

	public Personal_user() {
		super();
		// TODO Auto-generated constructor stub
	}

	@Override
	public String toString() {
		return "Personal_user [pid=" + pid + ", pname=" + pname + ", ppwd=" + ppwd + ", puname=" + puname + ", email="
				+ email + ", sex=" + sex + ", age=" + age + ", schName=" + schName + ", majName=" + majName + ", edu="
				+ edu + ", workComName=" + workComName + ", workJobName=" + workJobName + ", workContent=" + workContent
				+ "]";
	}

	public Integer getPid() {
		return pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public String getPname() {
		return pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	public String getPpwd() {
		return ppwd;
	}

	public void setPpwd(String ppwd) {
		this.ppwd = ppwd;
	}

	public String getPuname() {
		return puname;
	}

	public void setPuname(String puname) {
		this.puname = puname;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Integer getAge() {
		return age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getSchName() {
		return schName;
	}

	public void setSchName(String schName) {
		this.schName = schName;
	}

	public String getMajName() {
		return majName;
	}

	public void setMajName(String majName) {
		this.majName = majName;
	}

	public String getEdu() {
		return edu;
	}

	public void setEdu(String edu) {
		this.edu = edu;
	}

	public String getWorkComName() {
		return workComName;
	}

	public void setWorkComName(String workComName) {
		this.workComName = workComName;
	}

	public String getWorkJobName() {
		return workJobName;
	}

	public void setWorkJobName(String workJobName) {
		this.workJobName = workJobName;
	}

	public String getWorkContent() {
		return workContent;
	}

	public void setWorkContent(String workContent) {
		this.workContent = workContent;
	}

	private String workContent;

}