package com.chinasofti.model;

import org.springframework.stereotype.Component;

@Component
public class Person_conn_info {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_conn_info.Conn_Id
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     * 关系ID
     */
    private Integer connId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_conn_info.P_id
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     * 个人用户ID
     */
    private Integer pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_conn_info.Edu_id
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     * 教育背景ID
     */
    private Integer eduId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_conn_info.Work_id
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     * 工作经验Id
     */
    private Integer workId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_conn_info.Conn_Id
     *
     * @return the value of person_conn_info.Conn_Id
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public Integer getConnId() {
        return connId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_conn_info.Conn_Id
     *
     * @param connId the value for person_conn_info.Conn_Id
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public void setConnId(Integer connId) {
        this.connId = connId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_conn_info.P_id
     *
     * @return the value of person_conn_info.P_id
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_conn_info.P_id
     *
     * @param pId the value for person_conn_info.P_id
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_conn_info.Edu_id
     *
     * @return the value of person_conn_info.Edu_id
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public Integer getEduId() {
        return eduId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_conn_info.Edu_id
     *
     * @param eduId the value for person_conn_info.Edu_id
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public void setEduId(Integer eduId) {
        this.eduId = eduId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_conn_info.Work_id
     *
     * @return the value of person_conn_info.Work_id
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public Integer getWorkId() {
        return workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_conn_info.Work_id
     *
     * @param workId the value for person_conn_info.Work_id
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public void setWorkId(Integer workId) {
        this.workId = workId;
    }
}