package com.chinasofti.model;

import java.util.Date;

import org.springframework.stereotype.Component;

@Component
public class Personal_user {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column personal_user.pid
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 个人用户ID
	 */
	private Integer pid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column personal_user.ppwd
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 个人用户密码
	 * 
	 */

	private String pname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column personal_user.sex
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 用户性别
	 */
	private String ppwd;

	private String puname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column personal_user.pname
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 个人用户帐号
	 */

	private String sex;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column personal_user.birthday
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 用户出生日期
	 */
	private Integer age;

	public Personal_user(String puname, String sex, Integer age, String email) {
		super();
		this.puname = puname;
		this.sex = sex;
		this.age = age;
		this.email = email;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column personal_user.email
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 用户EMAIl
	 */
	private String email;

	public Integer getPid() {
		return pid;
	}

	public Personal_user() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Personal_user(Integer pid, String pname, String ppwd, String puname, String sex, int age, String email) {
		super();
		this.pid = pid;
		this.pname = pname;
		this.ppwd = ppwd;
		this.puname = puname;
		this.sex = sex;
		this.age = age;
		this.email = email;
	}

	@Override
	public String toString() {
		return "Personal_user [pid=" + pid + ", pname=" + pname + ", ppwd=" + ppwd + ", puname=" + puname + ", sex="
				+ sex + ", age=" + age + ", email=" + email + "]";
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public String getPname() {
		return pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	public String getPpwd() {
		return ppwd;
	}

	public void setPpwd(String ppwd) {
		this.ppwd = ppwd;
	}

	public String getPuname() {
		return puname;
	}

	public void setPuname(String puname) {
		this.puname = puname;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public int getAge() {
		return age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column personal_user.state
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017 用户现在工作状态
	 */

}