package com.chinasofti.model;

import java.util.Date;

import org.springframework.stereotype.Component;
@Component
public class Work_experience {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_experience.work_id
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     * 
     * 工作经验ID
     */
    private Integer workId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_experience.com_name
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     * 公司名称
     */
    private String comName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_experience.job_name
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     * 
     * 职位名称
     */
    private String jobName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_experience.start_date
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     * 
     * 开始时间
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_experience.end_date
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     * 
     * 结束时间
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_experience.work_content
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     * 
     * 工作内容
     */
    private String workContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_experience.work_id
     *
     * @return the value of work_experience.work_id
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public Integer getWorkId() {
        return workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_experience.work_id
     *
     * @param workId the value for work_experience.work_id
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public void setWorkId(Integer workId) {
        this.workId = workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_experience.com_name
     *
     * @return the value of work_experience.com_name
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public String getComName() {
        return comName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_experience.com_name
     *
     * @param comName the value for work_experience.com_name
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public void setComName(String comName) {
        this.comName = comName == null ? null : comName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_experience.job_name
     *
     * @return the value of work_experience.job_name
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_experience.job_name
     *
     * @param jobName the value for work_experience.job_name
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_experience.start_date
     *
     * @return the value of work_experience.start_date
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_experience.start_date
     *
     * @param startDate the value for work_experience.start_date
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_experience.end_date
     *
     * @return the value of work_experience.end_date
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_experience.end_date
     *
     * @param endDate the value for work_experience.end_date
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_experience.work_content
     *
     * @return the value of work_experience.work_content
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public String getWorkContent() {
        return workContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_experience.work_content
     *
     * @param workContent the value for work_experience.work_content
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    public void setWorkContent(String workContent) {
        this.workContent = workContent == null ? null : workContent.trim();
    }
}