package com.chinasofti.dao;

import org.springframework.stereotype.Repository;

import com.chinasofti.model.Company_user;
import com.chinasofti.model.Personal_user;

@Repository
public interface Company_userMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table company_user
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017
	 */
	int deleteByPrimaryKey(Integer cuserId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table company_user
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017
	 */
	int insert(Company_user record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table company_user
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017
	 */
	int insertSelective(Company_user record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table company_user
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017
	 */
	Company_user selectByPrimaryKey(Integer cuserId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table company_user
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017
	 */
	int updateByPrimaryKeySelective(Company_user record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table company_user
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017
	 */
	int updateByPrimaryKey(Company_user record);

	Company_user selectByPname(String pname);
}