package com.chinasofti.dao;

import com.chinasofti.model.company_user;

public interface company_userMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_user
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int deleteByPrimaryKey(Integer cuserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_user
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int insert(company_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_user
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int insertSelective(company_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_user
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    company_user selectByPrimaryKey(Integer cuserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_user
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int updateByPrimaryKeySelective(company_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_user
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int updateByPrimaryKey(company_user record);
}