package com.chinasofti.dao;

import com.chinasofti.model.Edu_background;

public interface Edu_backgroundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_background
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int deleteByPrimaryKey(Integer eduId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_background
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int insert(Edu_background record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_background
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int insertSelective(Edu_background record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_background
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    Edu_background selectByPrimaryKey(Integer eduId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_background
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int updateByPrimaryKeySelective(Edu_background record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_background
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int updateByPrimaryKey(Edu_background record);
}