package com.chinasofti.dao;

import com.chinasofti.model.edu_background;

public interface edu_backgroundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_background
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int deleteByPrimaryKey(Integer eduId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_background
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int insert(edu_background record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_background
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int insertSelective(edu_background record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_background
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    edu_background selectByPrimaryKey(Integer eduId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_background
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int updateByPrimaryKeySelective(edu_background record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_background
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int updateByPrimaryKey(edu_background record);
}