package com.chinasofti.dao;

import com.chinasofti.model.Person_conn_info;

public interface Person_conn_infoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_conn_info
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int deleteByPrimaryKey(Integer connId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_conn_info
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int insert(Person_conn_info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_conn_info
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int insertSelective(Person_conn_info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_conn_info
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    Person_conn_info selectByPrimaryKey(Integer connId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_conn_info
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int updateByPrimaryKeySelective(Person_conn_info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_conn_info
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int updateByPrimaryKey(Person_conn_info record);
}