package com.chinasofti.dao;

import com.chinasofti.model.personal_user;

public interface personal_userMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_user
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_user
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int insert(personal_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_user
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int insertSelective(personal_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_user
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    personal_user selectByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_user
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int updateByPrimaryKeySelective(personal_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_user
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int updateByPrimaryKey(personal_user record);
}