package com.chinasofti.dao;

import org.springframework.stereotype.Repository;

import com.chinasofti.model.Personal_user;

@Repository

public interface Personal_userMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table personal_user
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017
	 */
	int deleteByPrimaryKey(Integer pid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table personal_user
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017
	 */
	int insert(Personal_user record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table personal_user
	 * 
	 * @param pname
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017
	 */

	int insertSelectiveRegister(Personal_user record);

	int insertSelective(Personal_user record, String pname);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table personal_user
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017
	 */
	Personal_user selectByPrimaryKey(Integer pid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table personal_user
	 * 
	 * @param pname
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017
	 */
	int updateByPnameSelective(String puname, String sex, Integer age, String email, String pname);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table personal_user
	 *
	 * @mbggenerated Tue Jul 18 11:12:09 CST 2017
	 */
	int updateByPrimaryKey(Personal_user record);

	/**
	 * 通过页面输入的帐号去数据库中盘查找与之对应的账户
	 * 
	 * @param pname
	 * @return
	 */
	Personal_user selectByPname(String pname);

	Personal_user AlterPUserPassword(String pusername, String ppw);

	int updateEduSelective(String schName, String majName, String edu, String pname);
	
	int updateWorkSelective(String comName, String jobName, String workContent, String pname);
	
	int alterPUserPassword(Personal_user user);
}