package com.chinasofti.dao;

import com.chinasofti.model.Project_experience;

public interface Project_experienceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_experience
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int insert(Project_experience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_experience
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int insertSelective(Project_experience record);
}