package com.chinasofti.dao;

import com.chinasofti.model.project_experience;

public interface project_experienceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_experience
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int insert(project_experience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_experience
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int insertSelective(project_experience record);
}