package com.chinasofti.dao;

import com.chinasofti.model.Work_experience;

public interface Work_experienceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int deleteByPrimaryKey(Integer workId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int insert(Work_experience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int insertSelective(Work_experience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    Work_experience selectByPrimaryKey(Integer workId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int updateByPrimaryKeySelective(Work_experience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int updateByPrimaryKey(Work_experience record);
}