package com.chinasofti.dao;

import com.chinasofti.model.work_experience;

public interface work_experienceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int deleteByPrimaryKey(Integer workId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int insert(work_experience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int insertSelective(work_experience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    work_experience selectByPrimaryKey(Integer workId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int updateByPrimaryKeySelective(work_experience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Tue Jul 18 11:12:09 CST 2017
     */
    int updateByPrimaryKey(work_experience record);
}